version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: quay.io/mojanalytics/user-guidance:latest
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build the user guidance
          command: |
            bundle exec middleman build --build-dir docs
      - run:
          name: Replace .nojekyll
          command: |
            touch docs/.nojekyll
      - persist_to_workspace:
          root: ~/project/user-guidance/docs/
          paths:
            - "*"
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: ~/project/user-guidance/docs/
      - aws-s3/sync:
          from: ~/project/user-guidance/docs
          to: "s3://user-guidance.analytical-platform.services.justice.gov.uk"

workflows:
  version: 2
  build-only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
