version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: ruby:2.6.3-alpine
    working_directory: ~/project
    steps:
      - run:
          name: Install system dependencies
          command: |
            apk update
            apk add --no-cache build-base nodejs npm git openssh-client bash
      - checkout
      - run:
          name: Install Ruby dependencies
          command: |
            gem install bundler:2.2.8
            bundle install
      - run:
          name: Build the user guidance
          command: |
            bundle exec middleman build --build-dir docs
      - run:
          name: Replace .nojekyll
          command: |
            touch docs/.nojekyll
      - persist_to_workspace:
          root: ~/project/docs/
          paths:
            - "*"
  deploy:
    docker:
      - image: "circleci/python:2.7"
    steps:
      - attach_workspace:
          at: ~/project/docs/
      - aws-s3/sync:
          arguments: '--delete'
          from: ~/project/docs
          to: "s3://user-guidance.analytical-platform.services.justice.gov.uk"

workflows:
  version: 2
  build-only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
