# Host to use for canonical URL generation (without trailing slash)
host: https://user-guidance.analytical-platform.service.justice.gov.uk

# Header-related options
show_govuk_logo: false
service_name: Analytical Platform User Guidance
service_link: https://user-guidance.analytical-platform.service.justice.gov.uk

# Links to show on right-hand-side of header
header_links:
  Control Panel: https://controlpanel.services.analytical-platform.service.justice.gov.uk/
  Status: https://status.analytical-platform.service.justice.gov.uk/
  Support: https://github.com/ministryofjustice/data-platform-support/issues/new/choose

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
# ga_tracking_id: G-R6XQGCZFY1

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: moj-analytical-services/user-guidance

# Slack options
owner_slack_workspace: mojdt
default_owner_slack: '#analytical-platform'

footer_links:
  Get in touch by email: mailto:analytical-platform@digital.justice.gov.uk
  Get in touch by Slack: https://moj.enterprise.slack.com/archives/C06TFT94JTC

redirects:
  /raise-a-feature-request.html: https://github.com/ministryofjustice/analytical-platform/issues/new?assignees=&labels=feature-request&projects=&template=feature-request-template.yml&title=+%E2%9C%A8+%3Ctitle%3E
  /raise-an-issue.html: https://github.com/ministryofjustice/data-platform-support/issues/new/choose
