name: Check for Broken Links

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "source/**"

jobs:
  check-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - uses: actions/checkout@v3
      - name: htmlproofer
        run: /scripts/check-url-links.sh
